### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by anastasiia-mirus**
Added a gif banner and moved the text to the left.

image

### CODE REVIEW

**Comment by anastasiia-mirus** [comment]
But there is also a possibility of choosing just the same banner but in jpeg format.

**Review by sergei-orloff — APPROVED** [review]
👍

**Review by AlenaGarnovskaya — COMMENTED** [review]
great

**Review by AlenaGarnovskaya — APPROVED** [review]
great

**Pull request merged**
