### PR TITLE
NASA Two browsers test for Google and Firefox added.

### PR DESCRIPTION
**Pull request by AlenaGarnovskaya**
Hi Team. Please check and approve my new test.

### CODE REVIEW

**Review by sergei-orloff — APPROVED** [review]

**Review by EkaterinaV886 — APPROVED** [review]

**Review by anastasiia-mirus — APPROVED** [review]
Works great!

**Comment by sergei-orloff** [comment]
Alena,
You need to resolve the conflict to merge the commit:

Screenshot_1

**Comment by AlenaGarnovskaya** [comment]
Sergey, do you know, if I close this pull reques and crete a new one, would it work?

**Comment by sergei-orloff** [comment]
@AlenaGarnovskaya I think so. I've done such things before.

**Comment by AlenaGarnovskaya** [comment]
@sergei-orloff thank you

**Comment by AlenaGarnovskaya** [comment]
Im closing this pull request and will open a new one.

**Pull request closed without merging**
